### ISSUE TITLE
Docker 설정

### ISSUE THREAD

**Issue by ingyeoking13** [boostcampwm-2021/web03-boocamWiki#13]
## 설명
개발 서버에서 Docker 를 수행할 수 있도록 준비 한다.
그에 따라 프로젝트에서 사용될 .env 파일 metadata에 들어갈 정보를 고민해본다.

## 작업 내용
- [x] Nginx docker image 작성
- [x] node docker image 작성
- [x] mysql docker image 작성
- [x] 사양서 정리

blocked by #9 #12

**Comment by wil953742** [comment]
3주차 스프린트로 이관합니다.
