### ISSUE TITLE
CI/CD 를 위한 스크립트 작성 및 테스트

### ISSUE THREAD

**Issue by ingyeoking13** [boostcampwm-2021/web03-boocamWiki#14]
## 설명
Github Workflow를 활용하여 Continuous Delivery를 달성해본다.
push/pull request 이벤트는 release 브랜치에 대해 구독한다.

## 작업 내용
- [x] Secret Key를 등록한다.
- [x] yaml 을 작성 및 main 브랜치에 merge한다.
- [x] PR 부터 yaml 스크립트까지 정상동작하는지 테스트한다.

blocked by #9 #12 #13

**Comment by wil953742** [comment]
3주차 스프린트로 이관합니다.
