### ISSUE TITLE
위키 고도화 작업

### ISSUE THREAD

**Issue by wil953742** [boostcampwm-2021/web03-boocamWiki#148]
## 작업 내용
- [x] 로고 타이틀
- [x] 대문 외부로 빼기
- [x] 버튼 라벨
- [x] 로그인 시 문서 작성 기능
- [x] 문서 없을 때 404 페이지 말고 다른 페이지 보여주기 (검색페이지 또는..)
- [x] 동시 편집 불가하도록. 동시 편집시 뒤 사용자에게 안내 문구를 표출한다.
- [x] 문서 작성 또는 편집 페이지서 페이지 이동시 페이지를 떠나시겠습니까 브라우저 default alert 띄우도록

## 웅일 11/24, 25
- [x] 아이디 기수 이름은 안바뀌는거 명시해주기!
- [x] 아이디, 이름 제약 더 걸기 ( 대문자 or 특수문자( 공백문자 )  방지 )
- [x] 버튼 디자인
- [x] 편집페이지 작성페이지랑 동기화
- [x] 클릭, 스크롤 이벤트 막기
- [x] 헤더 메뉴 변경
- [x] 카드에 링크 입력 고민
- [x] 이미지 찌그러지는 거 고민
- [x] 써드파티 통계 자료
- [x] 전체 문서 보는 페이지
- [x] 404 페이지 수정
- [x] 검색엔진 최적화
- [x] 본문 꾸밈 버튼 추가

**Comment by ingyeoking13** [comment]
![ERD 2021.11.28](https://user-images.githubusercontent.com/18030634/143823163-1d532d5d-a989-475f-b3fb-c9db92a2b01d.png)

**Comment by LeeKwang-min** [comment]
고생하셨습니다!
