### ISSUE TITLE
[설정] aws 서비스 요금 검토 부탁

### ISSUE THREAD

**Issue by ingyeoking13** [boostcampwm-2021/web03-boocamWiki#179]
## 온디맨드 비용
저희 서비스 빌드할 땐 적어도 t2.small이 필요합니다.  
t2.small 온디맨드 가격이 너무 비쌉니다. ㅠㅠㅠㅠㅠㅠㅠ 🥲
![image](https://user-images.githubusercontent.com/18030634/153703932-367ff054-fcef-4531-bdb2-d110790d88ad.png)
t2.small + 이전세대 HDD 50GB = 32.01 usd
32.01 * 36개월 = 1152.36 USD = 1,382,596 원 
3년 유지비 약 140만원입니다. (환율 22.02.12 일 기준 고려)

## 예약인스턴스, Savings Plan 
예약인스턴스, Savings Plan을 사용하려고 하는데요. [참고영상](https://www.youtube.com/watch?v=hscwZJgF6Fc) 

예약 인스턴스의 경우 인스턴스를 고정하여 사용합니다. 또는 컨버터블 옵션인경우 다른 인스턴스와 교환 가능합니다. small 로 구매한 경우 4micro를 운용가능. [참고영상2](https://www.youtube.com/watch?v=MHIKINUxVtQ&ab_channel=AWS%EA%B0%95%EC%9D%98%EC%8B%A4)

Savings Plan은 시간당 요금을 결정하고 그 요금 내에서 서비스를 이용하는 것으로 보입니다. Computes Savings plan 또는 EC2 Savings Plan으로 나뉩니다. 전자인 경우 연산이 필요한 EC2, Fargate, Lambda를 사용할 수 있습니다. 후자인 경우 EC2만 사용가능합니다. 다만 언제든지 동일한 패밀리 내로 이전 가능합니다. t2.compact -> t2.small -> t2.medium 등등

예약인스턴스, Savings Plan 비교표 (약정인 경우 바꿀수 없음을 의미)
![image](https://user-images.githubusercontent.com/18030634/153704058-a905b42b-fe64-4c62-9d20-99527639fa12.png)

## 예약 인스턴스

인스턴스를 고정하는 표준 예약 인스턴스의 경우 EC2 Savings Plan 요금과 같습니다. 아래 Savings Plan에서 확인 부탁드립니다.

컨버터블 인스턴스의 경우 (인스턴스 점수제로 다른 인스턴스로 교환 가능)
![image](https://user-images.githubusercontent.com/18030634/153705004-ade22353-bad7-41fd-a87f-4cc75709bfae.png)

347.00 + 4 * 36 = 491 USD = 589,099 원
3 년 유지비 약 59만원입니다.

## Savings Plan 비용 
t2.small 3년 선결제

![image](https://user-images.githubusercontent.com/18030634/153704762-0f7647b2-d672-495c-b398-78a8217e582c.png)

289.08 + 4 *36 = 433.08 USD = 519,607 원 
3년 유지비 약 52만원입니다. 

예약 인스턴스, Savings Plan 검토부탁드립니다.
컨버터블 인스턴스 59만원 /4인 => 1인당 3년 14만 7500원 => 년 4만 9천원 => 월 4100원 정도입니다. 
Savings Plan 52만원 / 4인 => 1인당 3년 13만원 => 년 4만 3333원 => 월 3600원 정도입니다.

근데 이게 배포용 한 개 거든요. 개발 서버도 둔다고 하면은 ... 🥲🥲🥲  
개발 서버는 개발기간동안만 온디맨드로 둬도 괜찮을 듯 합니다만 중지시에도 월 4천원 정도의 EBS 요금이 부과됩니다.

**Comment by 0xsuky** [comment]
개발도 있다면 ㄷㄷ하겠네요
![image](https://user-images.githubusercontent.com/53328838/153719005-6f79807d-9cc0-425b-8bc8-ee8580b3b10f.png)
![image](https://user-images.githubusercontent.com/53328838/153719016-059cc811-f411-4a94-bb97-57bf6cd7dd0b.png)
![image](https://user-images.githubusercontent.com/53328838/153719021-07131576-cca8-41e4-bc0e-2a6724b0a0d5.png)
https://calculator.aws/#/createCalculator/EC2 여기에서 계산을 해봤는데 조금 더 싸게 나오는 것 같아요.
vCpu 2개, Memory 2GB면 Small이고 Reserved Instance 방식으로 확인해봤어요.
너무 싸게 나온 것 같아서 제가 뭔가 계산이 안 된 부분이 있을 수도 있을 것 같습니다 ㅎㅎ;;
저거 말고도 오브젝트 스토리지 비용도 계산해봐야 할 것 같습니다. 😀 (AWS에 비해선 엄청 쌉니다 ㅎㅎ)

**Comment by ingyeoking13** [comment]
@0xsuky 영수, 혹시 첫 번째 스크린샷 바로 아래에 어떤 인스턴스인지 나오는 데 그게 뭔지 알려줄 수 있어? 나는 t4g.small이야. 표준 예약 시간당 비용이 가장 낮은데 이 것 괜찮은것 같아!  나는 205.00USD가 나오긴하는데 아마 영수가 ***프리티어***라 그런가? ***학생***이라서그런가? EBS 비용도 약간 다르게 나오네! 나는 3.42USD야!
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/18030634/153741564-60035bdf-41fd-4292-8f64-f730b8c17c24.png">
205USD 면 EBS 비용 포함해서 대충 350USD고 한화로 40만원이라 젤 싼거같아! 
40만원에 4명이면 각 10만원씩, 월 2800원 부담이야!
166USD면 더 싸겠지?!

**Comment by 0xsuky** [comment]
다른 설정은 다 똑같은데 아마 지역이 `버지니아 북부`로 해서 그런 것 같아요. t4g.small은 똑같습니다 :)
![image](https://user-images.githubusercontent.com/53328838/153766184-c8d8df51-e1a3-4773-ad33-8c1a0c110390.png)
![image](https://user-images.githubusercontent.com/53328838/153766196-c7c37aee-4062-49d9-97be-1f55b13c4121.png)

**Comment by ingyeoking13** [comment]
ec2 t2.micro( 1vcpu 1gb ) 변경완료 (구매도함)
