### ISSUE TITLE
GNB에는 검색을 수행할 수 있는 검색창이 있다.

### ISSUE THREAD

**Issue by ingyeoking13** [boostcampwm-2021/web03-boocamWiki#26]
## 설명
GNB에는 검색창이 있으며, 사용자는 검색을 수행할 수 있다.

## 작업 내용
- [x] 검색창에는 검색어를 입력할 수 있다.

**Comment by LeeKwang-min** [comment]
남은 내용은 #50 으로 이관합니다.
