### ISSUE TITLE
GNB에는 로그인/로그아웃 버튼이 위치한다.

### ISSUE THREAD

**Issue by ingyeoking13** [boostcampwm-2021/web03-boocamWiki#27]
## 설명
.

## 작업 내용
- [x] GNB에 로그인/로그아웃 버튼을 제공한다.
- [ ] 로그인/로그아웃 상태에 따라 버튼의 레이아웃이 달라진다
- [ ] 로그인/로그아웃 상태에 따라 클릭시 나타나는 메뉴가 다르다.

**Comment by LeeKwang-min** [comment]
남은 내용은 #55로 이관한다.
