### ISSUE TITLE
GNB에는 다른 페이지에 대한 네이게이터를 제공한다

### ISSUE THREAD

**Issue by ingyeoking13** [boostcampwm-2021/web03-boocamWiki#28]
## 설명
.

## 작업 내용
- [x] '각종 순위' 페이지로 이동할 수 있다.
- [x] '문서 작성' 페이지로 이동할 수 있다.
- [x] '위치 정보' 페이지로 이동할 수 있다.
- [ ] '문서 작성' 페이지로 이동시 사용자가 로그인 하지 않은 경우 로그인 여부에 대한 알람을 받을 수 있다.

**Comment by LeeKwang-min** [comment]
남은 내용은 #52로 이관합니다.
