### ISSUE TITLE
대문 수정은 관리자만 가능하다.

### ISSUE THREAD

**Issue by wil953742** [boostcampwm-2021/web03-boocamWiki#49]
## 설명
대문 수정 권한에 따른 UI 설정

## 작업 내용
- [x] 일반 사용자는 대문을 수정할 수 없다.
- [x] 관리자에게는 대문 수정 기능이 보인다.

**Comment by ingyeoking13** [comment]
대문은 정적 파일 정보로 제공하도록 사양변경하였습니다.
close합니다.
