### ISSUE TITLE
사용자는 작성된 문서를 열람할 수 있다.

### ISSUE THREAD

**Issue by wil953742** [boostcampwm-2021/web03-boocamWiki#57]
## 작업 내용
- [x] 사용자는 문서의 본문을 읽을 수 있다.
- [x] 사용자는 사용자 명찰을 확인할 수 있다.
- [x] 사용자는 url 파라미터로 해당 문서를 검색할 수 있다.
- [x] 사용자는 문서 목록을 확인할 수 있다.

**Comment by ingyeoking13** [comment]
스타일링 점검*
