### ISSUE TITLE
문서생성과 관련된 web api 정의

### ISSUE THREAD

**Issue by ingyeoking13** [boostcampwm-2021/web03-boocamWiki#7]
## 설명
문서생성과 관련된 web api를 정의하고,
문서 기록을 남긴다.

## 작업 내용
- [x] 문서 생성 기능 회의
- [x] 문서 생성 web api 정의
- [x] web api 사양 문서기록

**Comment by wil953742** [comment]
[API 명세 ](https://www.notion.so/kimsuky/API-e0493ab856524895ac440a526813cd73) 해당 링크에 정리했습니다.
