### ISSUE TITLE
ERD 작성

### ISSUE THREAD

**Issue by ingyeoking13** [boostcampwm-2021/web03-boocamWiki#8]
## 설명
부캠위키에 필요한 ERD를 작성하고 기록으로 남긴다.

## 작업 내용
- [x] 부캠위키 서비스 기능 회의
- [x] ERD 작성
- [x] ERD 내용 문서 기록

**Comment by wil953742** [comment]
1차 ERD 작성 후, 슬랙에 sql 파일과 노션에 이미지 업로드 했습니다.
