### ISSUE TITLE
개발서버 환경설정 - 1

### ISSUE THREAD

**Issue by ingyeoking13** [boostcampwm-2021/web03-boocamWiki#9]
## 설명
개발용 서버 구축 및 환경 설정한다.

## 작업 내용
- [x] nCloud 서버 인스턴스 생성
- [x] git 설정 (git pull, push via ssh) 
- [x] 개발 서버에서 사용자 계정 생성

**Comment by wil953742** [comment]
1. 서버 인스턴스 생성
2. git 계정 정보 없이 push/pull 설정
3. root 계정 사용
